// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculator/calculator_pb/calculator.proto

package calculatorpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Adding struct {
	Addone               int32    `protobuf:"varint,1,opt,name=addone,proto3" json:"addone,omitempty"`
	Addtwo               int32    `protobuf:"varint,2,opt,name=addtwo,proto3" json:"addtwo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Adding) Reset()         { *m = Adding{} }
func (m *Adding) String() string { return proto.CompactTextString(m) }
func (*Adding) ProtoMessage()    {}
func (*Adding) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b44e1cc294e667d, []int{0}
}

func (m *Adding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Adding.Unmarshal(m, b)
}
func (m *Adding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Adding.Marshal(b, m, deterministic)
}
func (m *Adding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Adding.Merge(m, src)
}
func (m *Adding) XXX_Size() int {
	return xxx_messageInfo_Adding.Size(m)
}
func (m *Adding) XXX_DiscardUnknown() {
	xxx_messageInfo_Adding.DiscardUnknown(m)
}

var xxx_messageInfo_Adding proto.InternalMessageInfo

func (m *Adding) GetAddone() int32 {
	if m != nil {
		return m.Addone
	}
	return 0
}

func (m *Adding) GetAddtwo() int32 {
	if m != nil {
		return m.Addtwo
	}
	return 0
}

type AddRequest struct {
	Adding               *Adding  `protobuf:"bytes,1,opt,name=adding,proto3" json:"adding,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b44e1cc294e667d, []int{1}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetAdding() *Adding {
	if m != nil {
		return m.Adding
	}
	return nil
}

type AddResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b44e1cc294e667d, []int{2}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*Adding)(nil), "calculator.Adding")
	proto.RegisterType((*AddRequest)(nil), "calculator.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "calculator.AddResponse")
}

func init() {
	proto.RegisterFile("calculator/calculator_pb/calculator.proto", fileDescriptor_5b44e1cc294e667d)
}

var fileDescriptor_5b44e1cc294e667d = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x4c, 0x4e, 0xcc, 0x49,
	0x2e, 0xcd, 0x49, 0x2c, 0xc9, 0x2f, 0xd2, 0x47, 0x30, 0xe3, 0x0b, 0x92, 0x90, 0x78, 0x7a, 0x05,
	0x45, 0xf9, 0x25, 0xf9, 0x42, 0x5c, 0x08, 0x11, 0x25, 0x0b, 0x2e, 0x36, 0xc7, 0x94, 0x94, 0xcc,
	0xbc, 0x74, 0x21, 0x31, 0x2e, 0xb6, 0xc4, 0x94, 0x94, 0xfc, 0xbc, 0x54, 0x09, 0x46, 0x05, 0x46,
	0x0d, 0xd6, 0x20, 0x28, 0x0f, 0x2a, 0x5e, 0x52, 0x9e, 0x2f, 0xc1, 0x04, 0x17, 0x2f, 0x29, 0xcf,
	0x57, 0xb2, 0xe0, 0xe2, 0x72, 0x4c, 0x49, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0xd2,
	0x02, 0xab, 0xca, 0xcc, 0x4b, 0x07, 0xeb, 0xe6, 0x36, 0x12, 0xd2, 0x43, 0xb2, 0x16, 0x62, 0x43,
	0x10, 0x54, 0x85, 0x92, 0x2a, 0x17, 0x37, 0x58, 0x67, 0x71, 0x41, 0x7e, 0x5e, 0x31, 0xd8, 0x82,
	0xa2, 0xd4, 0xe2, 0xd2, 0x9c, 0x12, 0x98, 0xc5, 0x10, 0x9e, 0x91, 0x1b, 0xd8, 0x82, 0xe0, 0xd4,
	0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x0b, 0x2e, 0x66, 0xc7, 0x94, 0x14, 0x21, 0x31, 0x34, 0x73,
	0xa1, 0xf6, 0x4b, 0x89, 0x63, 0x88, 0x43, 0x4c, 0x57, 0x62, 0x70, 0xe2, 0x8b, 0xe2, 0x41, 0xc8,
	0x15, 0x24, 0x25, 0xb1, 0x81, 0x43, 0xc1, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xc3, 0xa7, 0x23,
	0xc4, 0x32, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AddServiceClient is the client API for AddService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddServiceClient interface {
	//unary
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
}

type addServiceClient struct {
	cc *grpc.ClientConn
}

func NewAddServiceClient(cc *grpc.ClientConn) AddServiceClient {
	return &addServiceClient{cc}
}

func (c *addServiceClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/calculator.AddService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddServiceServer is the server API for AddService service.
type AddServiceServer interface {
	//unary
	Add(context.Context, *AddRequest) (*AddResponse, error)
}

// UnimplementedAddServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAddServiceServer struct {
}

func (*UnimplementedAddServiceServer) Add(ctx context.Context, req *AddRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}

func RegisterAddServiceServer(s *grpc.Server, srv AddServiceServer) {
	s.RegisterService(&_AddService_serviceDesc, srv)
}

func _AddService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.AddService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.AddService",
	HandlerType: (*AddServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _AddService_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calculator/calculator_pb/calculator.proto",
}
